version: "2"
services:
  nginx:
    image: nginx:latest
    container_name: NGINXDOCKERNAME2
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static  <--- HERE
    depends_on:
      - web
  web:
    build: .
    container_name: DJANGOXDOCKERNAME2
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - /static:/static    <---- HERE
    expose:
      - "8000"
    env_file:
      - ./.env.dev

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: PSQLDOCKERNAME2